<?xml version="1.0"?>
<package format="2">
  <name>dagger_msgs</name>
  <version>0.0.1</version>
  <description>Custom messages for FluxDAgger system</description>

  <maintainer email="hqr1092777015@gmail.com">Ryan Hu</maintainer>
  <license>MIT</license>

  <!-- Catkin build system -->
  <buildtool_depend>catkin</buildtool_depend>

  <!-- Message generation dependencies -->
  <build_depend>message_generation</build_depend>
  <build_depend>std_msgs</build_depend>
  <build_depend>sensor_msgs</build_depend>

  <!-- Runtime dependencies -->
  <exec_depend>message_runtime</exec_depend>
  <exec_depend>std_msgs</exec_depend>
  <exec_depend>sensor_msgs</exec_depend>

  <export>
  </export>
</package>
